repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
  - repo: https://github.com/Calinou/pre-commit-luacheck
    rev: v1.0.0
    hooks:
      - id: luacheck
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.16.1
    hooks:
    - id: stylua # or stylua-system / stylua-github

